// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:omt/main.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: androidApiKey,
    appId: '1:697432999713:web:7a8df1f53a32762ecba060',
    messagingSenderId: '697432999713',
    projectId: 'omt-5d93d',
    authDomain: 'omt-5d93d.firebaseapp.com',
    storageBucket: 'omt-5d93d.firebasestorage.app',
    measurementId: 'G-KYJY5KVBD2',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: androidApiKey,
    appId: '1:697432999713:android:8e8e8b6d2f27e0c8cba060',
    messagingSenderId: '697432999713',
    projectId: 'omt-5d93d',
    storageBucket: 'omt-5d93d.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: iosApiKey,
    appId: '1:697432999713:ios:7e70aa7ea93c637ccba060',
    messagingSenderId: '697432999713',
    projectId: 'omt-5d93d',
    storageBucket: 'omt-5d93d.firebasestorage.app',
    iosBundleId: 'com.example.omt',
  );

}